version: "3.9"
services:
  app:
    build: .
    container_name: arb-bot
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
